// Portafolio EPG USIL — programas vigentes desde octubre/noviembre 2026
// Generado desde PORTAFOLIO_NOV_EPG.xlsx. Para actualizar, reemplaza este arreglo.
const PROGRAMAS = [
  {
    "tipo": "PROGRAMA ESPECIALIZADO",
    "nombre": "CORPORATE COMPLIANCE",
    "eje": "DERECHO Y GOBIERNO CORPORATIVO"
  },
  {
    "tipo": "PROGRAMA ESPECIALIZADO",
    "nombre": "DERECHO DIGITAL Y TRANSFORMACIÓN LEGAL CON IA",
    "eje": "DERECHO Y GOBIERNO CORPORATIVO"
  },
  {
    "tipo": "PROGRAMA ESPECIALIZADO",
    "nombre": "OFICIAL DE DATOS PERSONALES ODP Y PROTECCIÓN DATOS",
    "eje": "DERECHO Y GOBIERNO CORPORATIVO"
  },
  {
    "tipo": "PROGRAMA ESPECIALIZADO",
    "nombre": "DERECHO LABORAL EMPRESARIAL",
    "eje": "DERECHO Y GOBIERNO CORPORATIVO"
  },
  {
    "tipo": "PROGRAMA ESPECIALIZADO",
    "nombre": "COMPETENCIAS DIGITALES E IA APLICADA PARA EDUCADORES",
    "eje": "EDUCACIÓN"
  },
  {
    "tipo": "PROGRAMA ESPECIALIZADO",
    "nombre": "GERENCIA Y CRECIMIENTO DE INSTITUCIONES EDUCATIVAS PRIVADAS",
    "eje": "EDUCACIÓN"
  },
  {
    "tipo": "PROGRAMA ESPECIALIZADO",
    "nombre": "METODOLOGÍA DE LA INVESTIGACIÓN",
    "eje": "EDUCACIÓN"
  },
  {
    "tipo": "PROGRAMA ESPECIALIZADO",
    "nombre": "APLICACIÓN DE LAS NORMAS INTERNACIONALES DE INFORMACIÓN FINANCIERA (NIIF)",
    "eje": "NEGOCIOS Y ESG"
  },
  {
    "tipo": "PROGRAMA ESPECIALIZADO",
    "nombre": "FINANZAS PARA NO FINANCIEROS: ANÁLISIS Y DECISIONES DE NEGOCIO",
    "eje": "NEGOCIOS Y ESG"
  },
  {
    "tipo": "PROGRAMA ESPECIALIZADO",
    "nombre": "FINTECH, BLOCKCHAIN Y ACTIVOS DIGITALES",
    "eje": "NEGOCIOS Y ESG"
  },
  {
    "tipo": "PROGRAMA ESPECIALIZADO",
    "nombre": "GESTIÓN DE COSTOS, PRESUPUESTOS Y RENTABILIDAD",
    "eje": "NEGOCIOS Y ESG"
  },
  {
    "tipo": "PROGRAMA ESPECIALIZADO",
    "nombre": "GESTIÓN DE TESORERÍA Y FUENTES DE FINANCIAMIENTO",
    "eje": "NEGOCIOS Y ESG"
  },
  {
    "tipo": "PROGRAMA ESPECIALIZADO",
    "nombre": "PLANEAMIENTO FINANCIERO Y CONTROL DE GESTIÓN",
    "eje": "NEGOCIOS Y ESG"
  },
  {
    "tipo": "PROGRAMA ESPECIALIZADO",
    "nombre": "PROTECCIÓN AL CONSUMIDOR Y GESTIÓN DE RECLAMOS",
    "eje": "ESCUELA DE GOBIERNO Y GESTIÓN PÚBLICA"
  },
  {
    "tipo": "PROGRAMA ESPECIALIZADO",
    "nombre": "CONTRACT MANAGEMENT PARA OBRAS PÚBLICAS E INFRAESTRUCTURA",
    "eje": "DERECHO Y GOBIERNO CORPORATIVO"
  },
  {
    "tipo": "PROGRAMA ESPECIALIZADO",
    "nombre": "GESTIÓN ESTRATÉGICA DE LA SOSTENIBILIDAD EMPRESARIAL",
    "eje": "NEGOCIOS Y ESG"
  },
  {
    "tipo": "PROGRAMA ESPECIALIZADO",
    "nombre": "GESTIÓN Y EXPANCIÓN DE FRANQUICIAS",
    "eje": "NEGOCIOS Y ESG"
  },
  {
    "tipo": "PROGRAMA ESPECIALIZADO",
    "nombre": "GESTIÓN Y PLANIFICACIÓN DE MYPES",
    "eje": "NEGOCIOS Y ESG"
  },
  {
    "tipo": "PROGRAMA ESPECIALIZADO",
    "nombre": "DISEÑO DE APPS & CHATBOTS CON IA",
    "eje": "INNOVACIÓN Y TI"
  },
  {
    "tipo": "PROGRAMA ESPECIALIZADO",
    "nombre": "INTELIGENCIA ARTIFICIAL PREDICTIVA PARA LÍDERES DE NEGOCIO",
    "eje": "INNOVACIÓN Y TI"
  },
  {
    "tipo": "PROGRAMA ESPECIALIZADO",
    "nombre": "CIBERSEGURIDAD DEFENSIVA Y OFENSIVA E IA APLICADA",
    "eje": "INNOVACIÓN Y TI"
  },
  {
    "tipo": "PROGRAMA ESPECIALIZADO",
    "nombre": "INNOVACIÓN APLICADA Y GESTIÓN ÁGIL DE PROYECTOS CON IA",
    "eje": "INNOVACIÓN Y TI"
  },
  {
    "tipo": "PROGRAMA ESPECIALIZADO",
    "nombre": "IA APLICADA A LA INNOVACIÓN PROFESIONAL",
    "eje": "INNOVACIÓN Y TI"
  },
  {
    "tipo": "PROGRAMA ESPECIALIZADO",
    "nombre": "TRANSFORMACIÓN ORGANIZACIONAL Y BUSINESS AGILITY",
    "eje": "LIDERAZGO Y GESTIÓN DE PERSONAS"
  },
  {
    "tipo": "PROGRAMA ESPECIALIZADO",
    "nombre": "COACHING PERSONAL Y ORGANIZACIONAL",
    "eje": "LIDERAZGO Y GESTIÓN DE PERSONAS"
  },
  {
    "tipo": "PROGRAMA ESPECIALIZADO",
    "nombre": "CERTIFICACIÓN INTERNACIONAL EN LIDERAZGO Y GESTIÓN DE EQUIPOS",
    "eje": "LIDERAZGO Y GESTIÓN DE PERSONAS"
  },
  {
    "tipo": "PROGRAMA ESPECIALIZADO",
    "nombre": "GESTIÓN DE TALENTO Y PERSONAS",
    "eje": "LIDERAZGO Y GESTIÓN DE PERSONAS"
  },
  {
    "tipo": "PROGRAMA ESPECIALIZADO",
    "nombre": "GESTIÓN DE INDICADORES EN RECURSOS HUMANOS",
    "eje": "LIDERAZGO Y GESTIÓN DE PERSONAS"
  },
  {
    "tipo": "PROGRAMA ESPECIALIZADO",
    "nombre": "CREADORES DIGITALES CON IA",
    "eje": "NEGOCIOS Y ESG"
  },
  {
    "tipo": "PROGRAMA ESPECIALIZADO",
    "nombre": "GERENCIA DE VENTAS",
    "eje": "NEGOCIOS Y ESG"
  },
  {
    "tipo": "PROGRAMA ESPECIALIZADO",
    "nombre": "MARKETING DIGITAL 4.0 & IA",
    "eje": "NEGOCIOS Y ESG"
  },
  {
    "tipo": "PROGRAMA ESPECIALIZADO",
    "nombre": "MARKETING Y GESTIÓN COMERCIAL",
    "eje": "NEGOCIOS Y ESG"
  },
  {
    "tipo": "PROGRAMA ESPECIALIZADO",
    "nombre": "SEO, GEO, GOOGLE ADS Y SOCIAL MEDIA",
    "eje": "NEGOCIOS Y ESG"
  },
  {
    "tipo": "PROGRAMA ESPECIALIZADO",
    "nombre": "CUSTOMER EXPERIENCE Y SERVICE DESIGN",
    "eje": "NEGOCIOS Y ESG"
  },
  {
    "tipo": "PROGRAMA ESPECIALIZADO",
    "nombre": "MARKETING PARA LA INDUSTRIA COSMÉTICA",
    "eje": "NEGOCIOS Y ESG"
  },
  {
    "tipo": "PROGRAMA ESPECIALIZADO",
    "nombre": "GESTIÓN DE CALIDAD Y OPERACIONES FARMACÉUTICAS",
    "eje": "SALUD"
  },
  {
    "tipo": "PROGRAMA ESPECIALIZADO",
    "nombre": "GESTIÓN DE CLÍNICAS",
    "eje": "SALUD"
  },
  {
    "tipo": "PROGRAMA ESPECIALIZADO",
    "nombre": "GESTIÓN FINANCIERA PARA CLÍNICAS",
    "eje": "SALUD"
  },
  {
    "tipo": "PROGRAMA ESPECIALIZADO",
    "nombre": "CIENCIA Y FORMULACIÓN COSMÉTICA: MAQUILLAJE - PRODUCTOS CAPILARES - MICROBIOLOGÍA Y DESARROLLO DE EMPAQUES",
    "eje": "SALUD"
  },
  {
    "tipo": "PROGRAMA ESPECIALIZADO",
    "nombre": "SEGURIDAD DEL PACIENTE Y CALIDAD EN ATENCIÓN SANITARIA",
    "eje": "SALUD"
  },
  {
    "tipo": "PROGRAMA ESPECIALIZADO",
    "nombre": "LIDERAZGO EN SALUD DIGITAL Y TELESALUD PARA EL PRIMER NIVEL DE ATENCIÓN",
    "eje": "SALUD"
  },
  {
    "tipo": "PROGRAMA ESPECIALIZADO",
    "nombre": "NUTRICIÓN DEPORTIVA APLICADA BASADA EN EVIDENCIA",
    "eje": "SALUD"
  },
  {
    "tipo": "PROGRAMA ESPECIALIZADO",
    "nombre": "CUIDADO Y ATENCIÓN INTEGRAL A PERSONAS DE SITUACIÓN DE DEPENDENCIA",
    "eje": "SALUD"
  },
  {
    "tipo": "PROGRAMA ESPECIALIZADO",
    "nombre": "ECONOMÍA DE LA SALUD Y GESTIÓN PRESUPUESTAL",
    "eje": "SALUD"
  },
  {
    "tipo": "PROGRAMA ESPECIALIZADO",
    "nombre": "CALIDAD Y MEJORA CONTINUA DE PROCESOS",
    "eje": "NEGOCIOS Y ESG"
  },
  {
    "tipo": "PROGRAMA ESPECIALIZADO",
    "nombre": "GESTIÓN ESTRATÉGICA DE COMPRAS Y ABASTECIMIENTO",
    "eje": "NEGOCIOS Y ESG"
  },
  {
    "tipo": "PROGRAMA ESPECIALIZADO",
    "nombre": "GESTIÓN DE INFRAESTRUCTURA Y SERVICIOS PORTUARIOS",
    "eje": "NEGOCIOS Y ESG"
  },
  {
    "tipo": "PROGRAMA ESPECIALIZADO",
    "nombre": "GESTIÓN DE HOTELES Y RESTAURANTES",
    "eje": "NEGOCIOS Y ESG"
  },
  {
    "tipo": "PROGRAMA ESPECIALIZADO",
    "nombre": "GESTIÓN ESTRATÉGICA DE SEGURIDAD, SALUD OCUPACIONAL Y MEDIO AMBIENTE (SSOMA)",
    "eje": "LIDERAZGO Y GESTIÓN DE PERSONAS"
  },
  {
    "tipo": "CURSO DE ESPECIALIZACIÓN",
    "nombre": "DISEÑO DE REPORTE DE SOSTENIBILIDAD Y ESG PARA EMPRESAS: ESTÁNDARES GRI Y NIIF S1/S2",
    "eje": "NEGOCIOS Y ESG"
  },
  {
    "tipo": "CURSO DE ESPECIALIZACIÓN",
    "nombre": "MARKETING ESTRATÉGICO PARA NEGOCIOS GASTRONÓMICOS",
    "eje": "NEGOCIOS Y ESG"
  },
  {
    "tipo": "CURSO DE ESPECIALIZACIÓN",
    "nombre": "COSTOS Y PRESUPUESTOS PARA RESTAURANTES",
    "eje": "NEGOCIOS Y ESG"
  },
  {
    "tipo": "CURSO DE ESPECIALIZACIÓN",
    "nombre": "CONTROL DE INVENTARIOS Y GESTIÓN DE OPERACIONES DE ALMACÉN",
    "eje": "NEGOCIOS Y ESG"
  },
  {
    "tipo": "CURSO DE ESPECIALIZACIÓN",
    "nombre": "GESTIÓN DE COMPENSACIONES Y BENEFICIOS SOCIALES",
    "eje": "LIDERAZGO Y GESTIÓN DE PERSONAS"
  },
  {
    "tipo": "CURSO DE ESPECIALIZACIÓN",
    "nombre": "ESTRATEGIAS DE VENTAS B2B: GESTIÓN DE CUENTAS Y OPORTUNIDADES",
    "eje": "NEGOCIOS Y ESG"
  },
  {
    "tipo": "CURSO DE ESPECIALIZACIÓN",
    "nombre": "CONVIVENCIA ESCOLAR Y PROTOCOLOS DE ACTUACIÓN (SÍSEVE)",
    "eje": "SALUD"
  },
  {
    "tipo": "CURSO DE ESPECIALIZACIÓN",
    "nombre": "GESTIÓN DE ACTIVACIONES DE MARCA Y EXPERIENCIAS COMERCIALES",
    "eje": "NEGOCIOS Y ESG"
  },
  {
    "tipo": "CURSO DE ESPECIALIZACIÓN",
    "nombre": "LEAN SIX SIGMA YELLOW BELT",
    "eje": "NEGOCIOS Y ESG"
  },
  {
    "tipo": "CURSO DE ESPECIALIZACIÓN",
    "nombre": "PUBLICIDAD INTELIGENTE CON ANDROMEDA EL NUEVO NÚCLEO DE META ADS",
    "eje": "NEGOCIOS Y ESG"
  },
  {
    "tipo": "CURSO DE ESPECIALIZACIÓN",
    "nombre": "TÉCNICAS COMERCIALES CON INTELIGENCIA ARTIFICIAL",
    "eje": "NEGOCIOS Y ESG"
  },
  {
    "tipo": "CURSO DE ESPECIALIZACIÓN",
    "nombre": "IA APLICADA AL PLANEAMIENTO FINANCIERO Y FORECASTING",
    "eje": "NEGOCIOS Y ESG"
  },
  {
    "tipo": "CURSO DE ESPECIALIZACIÓN",
    "nombre": "STORYTELLING FINANCIERO Y PRESENTACIONES EJECUTIVAS CON IA",
    "eje": "NEGOCIOS Y ESG"
  },
  {
    "tipo": "CURSO DE ESPECIALIZACIÓN",
    "nombre": "PREVENCIÓN DE LAVADO DE ACTIVOS Y ANTICORRUPCIÓN",
    "eje": "DERECHO Y GOBIERNO CORPORATIVO"
  },
  {
    "tipo": "CURSO DE ESPECIALIZACIÓN",
    "nombre": "HERRAMIENTAS LEGALTECH PARA ABOGADOS",
    "eje": "DERECHO Y GOBIERNO CORPORATIVO"
  },
  {
    "tipo": "CURSO DE ESPECIALIZACIÓN",
    "nombre": "ESTADOS FINANCIEROS CON INTELIGENCIA ARTIFICIAL: ANÁLISIS , INTERPRETACIÓN Y VISUALIZACIÓN",
    "eje": "NEGOCIOS Y ESG"
  },
  {
    "tipo": "CURSO DE ESPECIALIZACIÓN",
    "nombre": "ATRACCIÓN Y SELECCIÓN DE TALENTO",
    "eje": "LIDERAZGO Y GESTIÓN DE PERSONAS"
  },
  {
    "tipo": "CURSO DE ESPECIALIZACIÓN",
    "nombre": "ANÁLISIS DE DATOS FINANCIEROS CON BLOOMBERG",
    "eje": "NEGOCIOS Y ESG"
  },
  {
    "tipo": "CURSO DE ESPECIALIZACIÓN",
    "nombre": "PRESENTACIONES DE ALTO IMPACTO",
    "eje": "LIDERAZGO Y GESTIÓN DE PERSONAS"
  },
  {
    "tipo": "CURSO DE ESPECIALIZACIÓN",
    "nombre": "GAMIFICACIÓN DE PROCESOS EDUCATIVOS Y EMPRESARIALES",
    "eje": "EDUCACIÓN"
  },
  {
    "tipo": "CURSO DE ESPECIALIZACIÓN",
    "nombre": "BIOMÉCANICA CLÍNICA APLICADA AL MOVIMIENTO HUMANO",
    "eje": "SALUD"
  },
  {
    "tipo": "MAESTRÍA",
    "nombre": "MAESTRÍA EN ADMINISTRACIÓN DE NEGOCIOS - EXECUTIVE MBA",
    "eje": "NEGOCIOS Y ESG"
  },
  {
    "tipo": "MAESTRÍA",
    "nombre": "MAESTRÍA EN CIENCIAS EMPRESARIALES CON MENCIÓN EN GESTIÓN FINANCIERA",
    "eje": "NEGOCIOS Y ESG"
  },
  {
    "tipo": "MAESTRÍA",
    "nombre": "MAESTRÍA EN EDUCACIÓN CON MENCIÓN EN GESTIÓN DE LA EDUCACIÓN",
    "eje": "EDUCACIÓN"
  },
  {
    "tipo": "MAESTRÍA",
    "nombre": "MAESTRÍA EN EDUCACIÓN CON MENCIÓN EN DOCENCIA EN EDUCACIÓN SUPERIOR",
    "eje": "EDUCACIÓN"
  },
  {
    "tipo": "DOCTORADO",
    "nombre": "DOCTORADO EN EDUCACIÓN",
    "eje": "EDUCACIÓN"
  },
  {
    "tipo": "SEGUNDA ESPECIALIDAD",
    "nombre": "SEGUNDA ESPECIALIDAD PROFESIONAL EN DERECHO PENAL Y COMPLIANCE",
    "eje": "DERECHO Y GOBIERNO CORPORATIVO"
  },
  {
    "tipo": "SEGUNDA ESPECIALIDAD",
    "nombre": "SEGUNDA ESPECIALIDAD PROFESIONAL EN NUTRICIÓN ONCOLÓGICA",
    "eje": "SALUD"
  },
  {
    "tipo": "SEGUNDA ESPECIALIDAD",
    "nombre": "SEGUNDA ESPECIALIDAD PROFESIONAL EN TERAPIA FÍSICA Y REHABILITACIÓN DEL DEPORTE",
    "eje": "SALUD"
  },
  {
    "tipo": "SEGUNDA ESPECIALIDAD",
    "nombre": "SEGUNDA ESPECIALIDAD PROFESIONAL EN PSICOLOGÍA EN GESTIÓN ESTRATÉGICA DEL TALENTO HUMANO Y BIENESTAR LABORAL",
    "eje": "SALUD"
  }
];
